### ISSUE TITLE
Suggestion for good updates/development

### ISSUE THREAD

**Issue by rapejim** [monty68/uniled#13]
First of all, **THANK YOU SO MUCH** for developing this integration.
It is amazing!!!
I have a SP601E and it works perfect.

I want to write this issue to suggest you if you can do the commits in a new "dev" branch. When you have a few commits and you upgrade the version, you can merge it to the main branch.
Now when you commit to the main branch, HA prompts us with an update and it's very stressful, 😜.

![image](https://user-images.githubusercontent.com/7972545/208636505-417b13bf-fcb7-4192-b5b5-3dce31f8746b.png)
The image above shows how I updated with the previous commits (up to "Fix UI update when fx is cancelled") and now (before I have time to reboot to apply the downloaded changes) I have a new update.... 😅.

**Comment by monty68** [comment]
Thanks for the positive feedback and the suggestion, this is my first HA and Python development so it has been a steep learning curve including the development environment, tools, and best practices. I will undoubtedly look to manage the releases better in the future.

**Comment by dbuezas** [comment]
You can also consider using github releases so you have a place to put the version number and changelog. This way HACS won't notify everybody about commits on the main branch either.
Relevant docs: https://hacs.xyz/docs/publish/start/#versions

**Comment by monty68** [comment]
> You can also consider using github releases so you have a place to put the version number and changelog. This way HACS won't notify everybody about commits on the main branch either. Relevant docs: https://hacs.xyz/docs/publish/start/#versions

I was already doing this, creating releases, but I think only when added as a HACS recognized integration does the versioning work. Anyway, for an FYI, I have created a dev branch and will use going forward but also have a PR into HACS to make this a default integration under HACS. Once I figure out pipy and split the library out, I will attempt to get the integration added to HA as an official integration.
