### ISSUE TITLE
Not detecting SP611E

### ISSUE THREAD

**Issue by BlockArchitech** [monty68/uniled#2]
It appears that this component doesn't detect theSP611E controller I have, and doesn't appear to emit any log output whatsoever. 

![Screenshot 2022-12-06 at 5 46 45 PM](https://user-images.githubusercontent.com/49456798/206040569-398e4eb6-2908-4b5d-8a3b-e83bdb7c211a.png)

Is there any fix to this, or outstanding issue that needs resolved?

**Comment by BlockArchitech** [comment]
Curiously, it appears that this device presents itself as "Light Bar", instead of SP611E. I've seen many of these controllers named "Strip" or "Magic LED". This one seems to be named "Light Bar"
![Screenshot_20221206-175311.png](https://user-images.githubusercontent.com/49456798/206042005-27d3e5a2-81f6-443c-a07e-9950b19a4119.png)
![Screenshot_20221206-175326.png](https://user-images.githubusercontent.com/49456798/206042050-bacb4d4d-6278-45b4-b577-6593ceeb060d.png)

**Comment by monty68** [comment]
Can you enable logging in your configuration.yaml

`logger:
  default: warning
  logs:
    custom_components.uniled: debug`

and send me the log output for the BLE discovery please

**Comment by monty68** [comment]
Can you now enable debug logging for the HA Bluetooth component in your configuration.yaml
and confirm that HA can see your device.

`
 logs:
    homeassistant.components.bluetooth: debug
`

I suspect if there is no debug log showing for uniled then HA may not be detecting your device etc. So this will help me
try and track down what is going on.

**Comment by BlockArchitech** [comment]
I will as soon as possible.

**Comment by BlockArchitech** [comment]
Okay - here is the logs for the bluetooth scanner and manager.
[home-assistant_2022-12-09T17-16-26.157Z.log](https://github.com/monty68/uniled/files/10196732/home-assistant_2022-12-09T17-16-26.157Z.log)

**Comment by BlockArchitech** [comment]
Should also note I changed the device name from Light Bar to SP611E

**Comment by BlockArchitech** [comment]
@monty68 any updates?

**Comment by monty68** [comment]
I cannot see your device showing in the logs which suggests HA bluetooth is not seeing your device so it won't show up in uniled. Can you with all the logging still enabled do a complete reboot of your HA device, I.e. Full power off and on again.

**Comment by oigan** [comment]
@BlockArchitech i had the same issue, and it's worked after i deleted/unpaired the controller from his app, in my case BanlanX. After that, integration just popped up in home assistant and it was ready to configure it.

**Comment by BlockArchitech** [comment]
I have tried this

**Comment by monty68** [comment]
I don't think this is an issue with the UniLED integration, until you can confirm HA is seeing the device in its Bluetooth logs, I am unable to investigate further.

**Comment by BlockArchitech** [comment]
Further digging: the issue is not invalid, per se. It is an invalid issue. You can get it working via some hacky Bluetooth methods, but SP611E controllers are not well supported as of today.
