### ISSUE TITLE
Support SP620E

### ISSUE THREAD

**Issue by akubekov** [monty68/uniled#21]
Support the new device SP620E (https://aliexpress.ru/item/1005004701237118.html)

Device similar to SP617E

The device is visible for adding, but an error occurs when adding.
When adding, error: device not supported.
![image](https://user-images.githubusercontent.com/48700913/211390636-85ca6c5b-686a-43c4-b97f-699d6bd6e7f3.png)

**Comment by monty68** [comment]
I have ordered one so will take a few days to add support

**Comment by monty68** [comment]
Support added in v1.0.2
