### ISSUE TITLE
Add Support For SP608e Controller

### ISSUE THREAD

**Issue by MeowMeow1982** [monty68/uniled#28]
Would it be possible to get support added for the SP608e Controller, i have a couple of them. Id be more than happy to help with the Gatt codes if you could give me some help on how to get them?

It is of the same type as these and uses banlan to control via BLU.

I have got the light Blue app and manged to find the the Charetersics ID of FFE0 and it has the sub option of FFE1

I dont have an android device so am unable to use the BLU Sniffer Tool that i have seen mentioned alot. If you could offer any advise on how to find the GATT commands another way that would be brillaint and ill be happy to share and help work on a SP608e Profile. If the only way is with an android devices i might have to go purchase a cheap one. I have an android TV Box but i dont think it has BLU on it.

Thanks in advance
![sp60e](https://user-images.githubusercontent.com/115744510/235537501-8220a8eb-81c1-48a8-be50-3346383fec95.jpg)

**Comment by monty68** [comment]
I will need to get hold of one to be able to verify the implementation. Give me a few weeks.

**Comment by MeowMeow1982** [comment]
Hi, I know I haven’t replied recently to this request. My apologies. I have 2 of these devices at home at the moment as I have put in some devices running wled for them temporarily. I have lots of spare time over the next couple of months as work is quiet so If you happy to help advise me how to find the relevant ble information I’d love to help get this device listed. I have medium code/script knowledge/experince and have recently setup lots on esp32 devices in numerous ways round my house. Let me know if I can help with this. Many thanks

**Comment by monty68** [comment]
@MeowMeow1982 Thanks for this, I did try recently to purchase an SP602E and SP608E but unfortunately was scammed and lost my money, so I have not been able to progress myself fully.

Any help is really appreciated, I'll need to set up a temporary repo where we can experiment, I am confident I have the basics as similar to the SP601E, which I have. However, I am unsure of the notification format for more than 2 channels as well as any BLE commands for the triggers etc.

I'll be in touch when ready to progress.

**Comment by monty68** [comment]
@MeowMeow1982 , if you can install [v2.1.0 Beta 2](https://github.com/monty68/uniled/releases/tag/2.1.0-beta.2), this should now detect your SP608E device, but may not fully function correctly. I would really be interested in seeing the debug output to determine what the notification format looks like

**Comment by monty68** [comment]
Support added in v2.2.0
