### ISSUE TITLE
Multiple devices - SP107E

### ISSUE THREAD

**Issue by ilker-aktuna** [monty68/uniled#3]
## Version of the custom_component
just downloaded from Github. It should be the current version. I don't see any version info.

## Configuration

no extra configuration

## Describe the bug

I have 2 of the same devices (SP107E) but only one of them is detected by this component.
They had the default name (SP107E) 
Thinking this was the issue, I renamed one of them. But still the other one is detected.

what else can I try ?
is this not supported ? (multiple devices)

**Comment by ilker-aktuna** [comment]
Hi,

I figured this is not about multiple devices.
The component just does not detect the device. So I edited "ble_model.py" as a workaround.
I just made the "is_device_valid" function return True in any case.
With this I can add the device and then control.
I guess there are some constants in the code (manufacturer ID ?) which are filtering one of my SP107E
Where is that constant ?

Thanks

**Comment by monty68** [comment]
Please enable debugging for uniled and provide me with this line from your debug output so I can check the advertisement data for that particular device:

`2022-12-09 06:01:11.901 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP617E2: Set device AdvertisementData(local_name='SP617E2', manufacturer_data={20563: b"\x17\x10!\x06'\x00\x95="}, service_uuids=['0000e0ff-0000-1000-8000-00805f9b34fb'], rssi=-44)`

**Comment by ilker-aktuna** [comment]
from other thread I see that I should add:
logger:
default: warning
logs:
custom_components.uniled: debug
homeassistant.components.bluetooth: debug

to the configuration.yaml file.
But my config is almost empty. Where do I put these lines in config ?
and then how do I activate these logs ?

**Comment by ilker-aktuna** [comment]
I got it 👍 

```
2022-12-09 12:03:02.451 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP107E.int: Set device AdvertisementData(local_name='SP107E.int', manufacturer_data={65535: b'\n\x10\xb1\xfc'}, service_uuids=['0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-45)
2022-12-09 12:03:02.489 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP107E.ext: Set device AdvertisementData(local_name='SP107E.ext', service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-127)

```

**Comment by ilker-aktuna** [comment]
one device shows manufacturer data, the other does not.

**Comment by monty68** [comment]
> one device shows manufacturer data, the other does not.
> 

Yes a strange one, I'll do some more checking to see if there is another way to reliably detect

**Comment by ilker-aktuna** [comment]
Btw, I'm not sure which one was not being detected yesterday before I changed the ble_model.py file.

**Comment by monty68** [comment]
Please try v0.2.0 Beta to see if this fixes the issue

**Comment by ilker-aktuna** [comment]
I could not find a way to delete the added sp107e. How can I delete and test adding again ?
