### ISSUE TITLE
Possbile to use app too?

### ISSUE THREAD

**Issue by loopy321** [monty68/uniled#37]
It would be great to be able to also control from the BanlanX app or some other app as well as having the integration.

Right now the integration connects great, but the app on my phone is unable to reconnect.

**Comment by monty68** [comment]
No, it's HA or the app, these devices only support a single connection. I use the HA app on my phone to control them, so no need for the banlanx app

**Comment by loopy321** [comment]
> No, it's HA or the app, these devices only support a single connection. I use the HA app on my phone to control them, so no need for the banlanx app

@monty68 Thanks for the reply.  I saw there was an approach to use a HA disconnect time here:
https://github.com/dave-code-ruiz/elkbledom

Do you think something similar would be possible in uniled?
