### ISSUE TITLE
SP620E long distance

### ISSUE THREAD

**Issue by sergey08** [monty68/uniled#44]
Hello,

I have a SP620E working with a Home Assistant in a Raspberry Pi working fine.

Problem is that some times conection is lost because SP620E is in a long distance from raspberry.

Is there any way to replicate bluetooth signal? Could a I use a ESP32 for this propose?
Any idea?

Thanks in advance

```

**Comment by monty68** [comment]
Take a look here [https://esphome.io/components/bluetooth_proxy.html](url)
