### ISSUE TITLE
SP63AE not detected despite being supported on 2.1.0-beta.2

### ISSUE THREAD

**Issue by l7ssha** [monty68/uniled#45]
## Version of the custom_component

2.1.0-beta.2

## Configuration

default

## Describe the bug
SP63AE not detected despite being supported per readme in dev_v2 branch. 
Using https://pl.aliexpress.com/item/1005006048326863.html?spm=a2g0o.order_list.order_list_main.5.c27e1c24kmYcFS&gatewayAdapt=glo2pol

## Debug log

```text
2024-01-05 12:08:29.118 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Checking support for: '32:00:00:00:1A:A6' (SP63AE)... AdvertisementData(local_name='SP63AE', manufacturer_data={20563: b')\x102\x00\x00\x00\x1a\xa6'}, service_uuids=['0000e0ff-0000-1000-8000-00805f9b34fb'], rssi=-127)
2024-01-05 12:08:29.118 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Device '32:00:00:00:1A:A6' (SP63AE) not supported!
```

**Comment by l7ssha** [comment]
Fixed problem with controller not being recognized in https://github.com/monty68/uniled/pull/46 . After being able to control LED strip seems like GREEN and RED are swapped on FW1906 LED strip - is there some kind of configuration for that?

**Comment by monty68** [comment]
> Fixed problem with controller not being recognized in #46 . After being able to control LED strip seems like GREEN and RED are swapped on FW1906 LED strip - is there some kind of configuration for that?

Hi, the pull request to fix SP63AE was against the wrong repo (dev_v2), where as the current latest dev repo is dev_zng, but no worries, I have replicated the change and will be merging all the dev repos very shortly and pushing the changes out as final.

On the color ordering issue, you can of course use the banlanx app itself, but in HA, once you have detected and installed a device, you can use the device "CONFIGURE" feature in HA which will allow you to change the color ordering.

<img width="355" alt="CONFIGURE" src="https://github.com/monty68/uniled/assets/4341648/df8590f4-b6f7-4eb9-a061-61beca98d017">
