### ISSUE TITLE
Adding effect selection directly on dashboard

### ISSUE THREAD

**Issue by ilker-aktuna** [monty68/uniled#5]
I am not sure if this is already available. I just could not figure it out if it is possible.
I want to be able to change effects directly with a pulldown setting on the card. (like the mode setting)
Is it possible to add it ?

Thanks

**Comment by monty68** [comment]
You can select effects from a drop-down within the standard HA interface for lights, but the light has to be on to see it.

![effects](https://user-images.githubusercontent.com/4341648/206507103-a7a7f9f6-7a08-4eb6-a90a-12d8d19b1540.jpg)

**Comment by BlockArchitech** [comment]
@ilker-aktuna, that would be something to do with a custom Lovelace UI card, not the actual light platform.

**Comment by ilker-aktuna** [comment]
ok. what is a lovelace card and how can I  get it ?
