### ISSUE TITLE
Effect speed sensitivity

### ISSUE THREAD

**Issue by ilker-aktuna** [monty68/uniled#6]
I am using the component with 2 SP107E devices.
The effect setting on the card is available from 1 to 186
But 1 is not slow enough.
So if I select 1, it is like 50% on the bluetooth mobile app.
I mean when I want to make it really slow, it is not possible from this component. But it is possible on the mobile app.

**Comment by monty68** [comment]
I cannot replicate any issue with setting speed or sensitivity, the ranges are correct and I can set the speed of my 107's to '1' without issue. Enable debugging and provide logs where you are changing the speed using HA so I can confirm the command being sent to the device and the status response which the device will confirm what setting it is using.

**Comment by ilker-aktuna** [comment]
I was wrong.
I had thought that it should stop moving if I set the min speed (1) 
But now I checked on the mobile app. Also there , it does not stop moving.
So I think we can close this issue.
Sorry.

**Comment by monty68** [comment]
> I was wrong.
> I had thought that it should stop moving if I set the min speed (1) 
> But now I checked on the mobile app. Also there , it does not stop moving.
> So I think we can close this issue.
> Sorry.

No worries, thanks for confirming
