### ISSUE TITLE
SP630E - Does not allow color change when solid color is selected

### ISSUE THREAD

**Issue by diegogsoares** [monty68/uniled#70]
I have just installed a new SP630E to Home assistant and cannot change colors when solid color is set.

Home Assistant version: 2024.7.4

UNILED version: 2.2.5

Device Info:
RGB(CW) SPI/PWM (Music) Controller by SPLED (BanlanX)
Firmware: V3.0.19
Hardware: SP630E

Light Configuration Type: SPI - RGB
Light mode: Static Color

LED Strip: PAUTIX IP65 Waterproof RGB Smart IC COB LED Strip Light Addressable

Unfortunately I cannot change colors in Home Assistant, when I configure other Light Configuration Types, I can, but the colors are all mixed up. With SPI - RGB I only get to turn on and off the light, it does not allow me to choose color or brightness.

**Comment by jonascoenen005** [comment]
+1 also have this issue!

**Comment by jonascoenen005** [comment]
@diegogsoares you can fix it by going to the uniled integration > Hubs > find your led strip and click "configure" > configure device > change "SPI - RGB" to "SPI - RGB + 1 CH PWM". This at least solved it for me!

**Comment by homeassistantjunkie** [comment]
@jonascoenen005 I have SP633 with similar issue.. But I don't have those options.. Only options I have are RGB, BRG, RBG...
(which I assume are positions of led diodes) But yea.. still didn't figure it out sadly.. :( +1

**Comment by monty68** [comment]
I need some log details to see what is going on asi cannot replicate as I don't have a physical device
