### ISSUE TITLE
SP636E - no brightness control

### ISSUE THREAD

**Issue by yenzic** [monty68/uniled#73]
Brightness is not displayed as an entity in the SP636E controller. Only  "on and off". Can you fix this?"

**Comment by sacilot** [comment]
same problem for sp630e

**Comment by sacilot** [comment]
![Screenshot_20241112_000708_Home Assistant](https://github.com/user-attachments/assets/e5fb7a34-a9b4-41f8-9f2f-61cd0867404b)
![Screenshot_20241111_235650_Home Assistant](https://github.com/user-attachments/assets/81702413-213d-4844-8a02-48264a5980a7)

**Comment by Sqeezerr** [comment]
hello, another problem is also the same with the sp637e, it's only turned on, but the brightness and cold/warm white enhancements don't work, it's CCT

**Comment by monty68** [comment]
> hello, another problem is also the same with the sp637e, it's only turned on, but the brightness and cold/warm white enhancements don't work, it's CCT

Have you updated to the latest Uniled version? Do you have any debug log files showing device interaction so I can see what the device is saying vs what HA is seeing?

**Comment by Sqeezerr** [comment]
United 3.0.8 beta fw banlan 3.0.19

Dňa po 16. 12. 2024, 9:48 Phil M ***@***.***> napísal(a):

**Comment by Sqeezerr** [comment]
it is possible to connect remotely and check where the error is

**Comment by Sqeezerr** [comment]
![Screenshot_2024-12-17-20-50-11-555_com android chrome](https://github.com/user-attachments/assets/db4ceb55-71a2-467a-8e06-ebdde3a8e3a1)
