### ISSUE TITLE
SP633E color issues

### ISSUE THREAD

**Issue by homeassistantjunkie** [monty68/uniled#77]
Hello,

I went through some issues that were already closed but didn't come across any like this one, although I see similar issues were fixed...

## Version of the custom_component
UniLed 2.2.5

YAML
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
bluetooth:
logger:

```

I got DIGITUS DN-30210-1 BT adapter and as soon as I pugged it in my SFF detected it and I was able to use it without any issues. 

I integrated HA UniLED v2.2.5 - The Universal Light Controller as I have 6 or 7 cheap LED strip controllers, models are SP633E and application that drives them is BanlanX.

Per UniLed description, this is a supported adapter but for some reason, I can only toggle it on/off and change mode from static to dynamic. I really want to be able to control light colors. Have in mind that via BanlanX, I am able to do so much fun stuff, but for HA I am only seeking option to change color of the light..


Please help! I don't want to throw away few of the controllers I have.. If we can resolve it, I would gladly buy you a coffee as I am doing this for a restaurant. 

I am not that tech savvy and I am willing to send any info you need!

Thanks in advance,
Mike

**Comment by monty68** [comment]
I need some log details to see what is going on asi cannot replicate as I don't have a physical device

**Comment by homeassistantjunkie** [comment]
Apologies Monty, as I said I am not tech savvy... I found this log under my Settings > Sys > Logs > SP633...
Let me know if this is the correct log. Thank you in advance for helping out, owners are still pushing me to complete this asap.. I will deff award you for landing me a hand...

[home-assistant_2024-11-10T21-23-43.832Z.log](https://github.com/user-attachments/files/17693109/home-assistant_2024-11-10T21-23-43.832Z.log)

**Comment by monty68** [comment]
Thanks, log is fine will look into resolving shortly

**Comment by homeassistantjunkie** [comment]
Hello kind sir, I see you closed the case, but nothing changed on my end.. I restarted HA instance and tried re-installing uniled.. However, all options are still the same. Do I need to get new adapters after all? Thank you for your dedication and replies.

**Comment by homeassistantjunkie** [comment]
Apologies, looks like color settings are added and working properly! Please send me your patreon or paypal!!

**Comment by monty68** [comment]
No worries and welcome, you can buy me a coffee from the link below if you'd like. 

https://buymeacoffee.com/monty68
