### ISSUE TITLE
Setting color should cancel effects 

### ISSUE THREAD

**Issue by dbuezas** [monty68/uniled#9]
If any effect is active, color selection has no effect.
I believe this not to be the standard expected behavior, as all my other led lamps automatically disable effects when a color is picked from the color wheel.

Thanks for the component, it works really well and it's so comprehensive! Awesome job!

**Comment by monty68** [comment]
Thanks for the feedback it is appreciated, in terms of your issue, which device model are you using?

**Comment by dbuezas** [comment]
It's an sp611e.
I'm playing with it right now and i see that some effects do react to the color wheel (e.g the single color vumeter). I guess this makes my issue irrelevant.

**Comment by monty68** [comment]
I can change functionality if a non sound effect is in operation it is cancelled when changing color.

**Comment by dbuezas** [comment]
That could make sense. Another alternative would be to change the light type to monochromatic in those cases (not sure that's possible)

**Comment by monty68** [comment]
OK, quick fix is to cancel and revert to a solid color, can do this in the next few mins. When I get more time I'll look at other options

**Comment by dbuezas** [comment]
:) thanks!
Let me know when to update if you want quick feedback

**Comment by monty68** [comment]
v0.2.5 should be ready for testing

**Comment by dbuezas** [comment]
Seems to work fine!
Just two minor details:
* The UI jumps quickly between selected color and old color (I assume this is because home assistant schedules an update right after each setter is called)
* Effects that use the microphone but don't care about the selected color don't get disabled when using the color wheel (e.g gradient and full color ejection forward)

**Comment by monty68** [comment]
I can fix both of these when I get some more time but will be done this week.

**Comment by monty68** [comment]
Fixed in v0.2.6 Beta

**Comment by dbuezas** [comment]
Feels solid!
